require: rubocop-performance

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/AbcSize:
  AllowedMethods:
    - as_json

Metrics/MethodLength:
  AllowedMethods:
    - as_json

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"

Style/StringLiterals:
  EnforcedStyle: double_quotes
