require: rubocop-performance

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"

Style/StringLiterals:
  EnforcedStyle: double_quotes
