compress_html:
  clippings: all

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.markdown
  - bin
  - lib
  - netlify.toml
  - vendor

sass:
    style: compressed
