baseurl: "/hockey"

compress_html:
  clippings: all

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

sass:
    style: compressed
