name: Nightly Deploy

on:
  schedule:
    - cron: "0 8 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger a build on Netlify
        shell: bash
        env:
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d {} "$NETLIFY_BUILD_HOOK"
